In [1]:
import numpy as np

image = np.array([
    [1, 1, 2, 4, 5],
    [5, 6, 7, 8, 9],
    [9, 8, 7, 6, 5],
    [5, 4, 3, 2, 1],
    [1, 2, 3, 4, 5]
])


In [2]:
kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])


In [3]:
def convolution(image, kernel):
    h, w = image.shape
    kh, kw = kernel.shape
    output = np.zeros((h - kh + 1, w - kw + 1))

    for i in range(output.shape[0]):
        for j in range(output.shape[1]):
            region = image[i:i+kh, j:j+kw]
            output[i, j] = np.sum(region * kernel)

    return output


In [4]:
conv_out = convolution(image, kernel)
print(conv_out)


[[-1. -3. -3.]
 [ 2.  2.  2.]
 [ 2.  2.  2.]]


In [5]:
def relu(x):
    return np.maximum(0, x)

relu_out = relu(conv_out)


In [6]:
def max_pooling(feature_map, size=2, stride=2):
    h, w = feature_map.shape

    out_h = (h - size) // stride + 1
    out_w = (w - size) // stride + 1

    output = np.zeros((out_h, out_w))

    out_i = 0
    for i in range(0, h - size + 1, stride):
        out_j = 0
        for j in range(0, w - size + 1, stride):
            region = feature_map[i:i+size, j:j+size]
            output[out_i, out_j] = np.max(region)
            out_j += 1
        out_i += 1

    return output


In [7]:
pooled_out = max_pooling(relu_out)
print(pooled_out)
print(pooled_out.shape)


[[2.]]
(1, 1)


In [8]:
flattened = pooled_out.flatten().reshape(1, -1)


In [9]:
# initialize weights
W = np.random.randn(flattened.shape[1], 1)
b = np.zeros((1, 1))

# forward pass
output = np.dot(flattened, W) + b
print("CNN Output:", output)


CNN Output: [[0.28925851]]


In [10]:
target = np.array([[1]])
loss = np.mean((target - output) ** 2)
print("Loss:", loss)


Loss: 0.505153458579406
